### ISSUE TITLE
image doesn't get full height

### ISSUE THREAD

**Issue by mulshankar13** [openopen114/MaterializeCarouselMobile#1]
image doesn't get ful height
can u please paste a a stackblitz working example?

**Comment by openopen114** [comment]
do you mean full screen?
i commit the full screen version on this repo, and stackblitz link blow
[https://stackblitz.com/edit/angular-scss-demo-yfdls4](https://stackblitz.com/edit/angular-scss-demo-yfdls4)

**Comment by mulshankar13** [comment]
Yeah. I guess it is working fine for small screen. But the moment you paste the link on laptop browser or  run the app on web browser the image is truncated in height.And the moment you resize the browser the image then occupies correctly the whole viewport. The ideal behaviour is that it should be occupying and readjusting accoridng to the whole viewport automatically. The next prev icons are missing anyways and the image doesn't slide. Please feel free to correct me.
