### ISSUE TITLE
The images don't occupy the whole viewport for web browser layout on launch

### ISSUE THREAD

**Issue by mulshankar13** [openopen114/MaterializeCarouselMobile#2]
I guess it is working fine for small screen. But the moment you paste the link on laptop browser or run the app on web browser the image is truncated in height.And the moment you resize the browser the image then occupies correctly the whole viewport. The ideal behaviour is that it should be occupying and readjusting accoridng to the whole viewport automatically. The next prev icons are missing anyways and the image doesn't slide. Please feel free to correct me.

**Comment by openopen114** [comment]
@mulshankar13 
i fix next prev icons and slide
[https://stackblitz.com/edit/angular-scss-demo-yfdls4](https://stackblitz.com/edit/angular-scss-demo-yfdls4)

**Comment by openopen114** [comment]
@mulshankar13 
i fix resize issue use resize event and init again

stackbiliz: [https://stackblitz.com/edit/angular-scss-demo-yfdls4](https://stackblitz.com/edit/angular-scss-demo-yfdls4)

live demo: [https://openopen114.github.io/MaterializeCarouselMobile/](https://openopen114.github.io/MaterializeCarouselMobile/)
